export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "@/global.css";
import { UserContextProvider } from "@/contexts/userContext";
import AdminNavBar from "../../components/NavBar/AdminNavBar";
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <UserContextProvider>
      <div className="flex min-h-screen">
        <div className="flex-none basis-[276px] grow-0 shrink">
          <AdminNavBar />
        </div>
        <div className="flex-1 p-6">{children}</div>
      </div>
    </UserContextProvider>
  );
}
