export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "@/global.css";
import { UserContextProvider } from "@/contexts/userContext";
import AdminNavBar from "../../components/NavBar/AdminNavBar";
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <UserContextProvider>
      {children}
      <AdminNavBar />
    </UserContextProvider>
  );
}
