name: Deploy to Staging
on:
  push:
    branches:
      - main

jobs:
  deploy_staging:
    name: Deploy to Staging
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: Staging
      firebaseProjectId: homework-dev-445619
      firebaseHostingChannelId: live
    secrets: inherit